title: <p align="center"> Peter Kusiak </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="">Resume</a> |
  <a href="https://www.linkedin.com/in/peterkusiak/">LinkedIn</a> |
  <a href="https://github.com/peterkusiak">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Working with Vielight Inc.
  <br>
  </p>



theme: jekyll-theme-minimal
